/**
 * Created by Wayuki on 25-Mar-17.
 */
export const AUTH_ACTIONS = {
  REGISTER_USER: 'REGISTER_AUTH_AUTHENTICATED_USER',
  LOGOUT_USER: 'LOGOUT_AUTH_AUTHENTICATED_USER',
};

export const SIDEBAR_ACTIONS = {
  TOGGLE: 'TOGGLE_APP_PAGE_SIDEBAR',
  SET: 'SET_APP_PAGE_SIDEBAR',
};

export const SEARCH_PAGE_ACTIONS = {
  HANDLE_QUERY_CHANGE: 'HANDLE_SEARCH_PAGE_QUERY_CHANGE',
  REGISTER_QUERY_RESULTS: 'REGISTER_SEARCH_PAGE_QUERY_RESULTS',
};

export default {};
